### ISSUE TITLE
Transparent mode?

### ISSUE THREAD

**Issue by mikaelsundin** [FeitianSmartcardReader/R502_SDK_Latest#1]
Do the R502 reader support transparent APDU to a NFC card? 

For example another reader ACR1252U support transparent via PCSC with following parameters:
Class : 0xFF
INS : 0x00
P1 : 0x00
P2 : 0x00

Also a API document of PCSC commands available on R502 could be nice.

**Comment by FeitianSmartcardReader** [comment]
What kind of card you will use?

**Comment by mikaelsundin** [comment]
I will use NT3H2211, page 47. 
And command SECTOR_SELECT

https://www.nxp.com/docs/en/data-sheet/NT3H2111_2211.pdf

**Comment by FeitianSmartcardReader** [comment]
Noted, would you mind send mail to me hongbin@ftsafe.com, I will forward to our sales to follow up, and possible to have it supports in technically speaking, thanks

**Comment by mikaelsundin** [comment]
Email is on the way.

**Comment by mikaelsundin** [comment]
Any updates on the subject?

**Comment by FeitianSmartcardReader** [comment]
@mikaelsundin sorry for late reply, is that still same request as before? read pages from NT3H2111_2211 and LPN8N04?
To read from Mifare Page: [0xFF, 0xB0, 0x00, PageNum, ReadLen] 
To write to Mifare Page: [0xFF, 0xD6, 0x00, PageNum, WriteLen, Data0, Data1, Data2, Data3]

**Comment by mikaelsundin** [comment]
Yes, still same request to access NT3H2111_2211 and LPN8N04.
NT3H2111_2211 implement some custom commands, thats why transparent mode to MiFare is intressting.

**Comment by FeitianSmartcardReader** [comment]
@mikaelsundin already add support, we are testing read 135 pages, if no problem, I will ship few samples to you for test. please send mail to hongbin@ftsafe.com with your address, then I can arrange the shipment, thanks

**Comment by FeitianSmartcardReader** [comment]
already supported.
