### ISSUE TITLE
Mifare Ultralight C on R502 CL

### ISSUE THREAD

**Issue by antonio-fr** [FeitianSmartcardReader/R502_SDK_Latest#3]
Model R502 CL
fw version 3.53

Any sector after 0x0F (0x10 and so on) can't be accessed. Read or write throw 0x6A82.
Card is formatted slot 3 = 0x E1 10 12 00. The card is not locked, can be written without auth. Lock bytes = 0 0 0 0. No memory protection : slot 0x42 AUTH0 = 0x30. This is the standard setup for a blank NDEF tag, writable as we want.
With other NFC reader brands, it works well to write the full card.

With R502, Any read or write operation with a slot sector address larger than 0x0F throws 0x6A82.

Example of writing :
```
-> FF D6 00 0E 04 31 32 33 64
<- 90 00
-> FF D6 00 0F 04 31 32 33 64
<- 90 00
-> FF D6 00 10 04 31 32 33 64
<- 6A 82
```

The MIFARE Ultralight C tags can be written (user data width) from address 4 to 39 (0x27). 4 bytes per sector, this makes 144 bytes for the NDEF data (including header). This issue of the Feitian reader, limits what can be read/write to 44 bytes, something like the old compatible Ultralight. Still, the documentation of the reader states "Mifare S50/S70/Ultralight C cards".

**Comment by FeitianSmartcardReader** [comment]
@antonio-fr  I will let our engineer to take a look, ultralight C using encryption inside the card, and the reader also need to be support.
let me talk to our engineer and back to you today, thanks

**Comment by antonio-fr** [comment]
Thank you. I think this has nothing to do with access or encryption. It seems the reader just can't tell the difference between Ultralight and Ultralight C, so it behaves with UltralightC cards as they are the "old" Ultralight (with a smaller memory).

**Comment by FeitianSmartcardReader** [comment]
@antonio-fr  u r right. we modified the firmware, and now it supports.
new firmware will send to you on tomorrow, keep update. ;-)

**Comment by antonio-fr** [comment]
Thanks. Reach me privately there : https://bitlogik.fr/contact.html

**Comment by FeitianSmartcardReader** [comment]
The issue fixed.
[R502B-3.54-fw.zip](https://github.com/FeitianSmartcardReader/R502_SDK_Latest/files/10285593/R502B-3.54-fw.zip)
